### PR TITLE
Add missing OrientDB modules to the binary

### PR DESCRIPTION
**Pull request by gytis**

### CODE REVIEW

**Comment by scottmarlow** [comment]
I verified that this now works!  Regarding testing, I'd like to try automating testing, by automatically running tests on OpenShift that use the OrientDB/Cassandra/MongoDB/Neo4j Swarm fractions to deploy an application that we can issue requests to.  I'm not sure of how to do this yet, but I believe that if we do, that we will end up with a better test environment, that can handle multi user load testing that runs over a period of time.  

I'd like to do the same for WildFly (using the OrientDB/Cassandra/MongoDB/Neo4j feature packs) as well.

Does this make sense to you?  Does it make sense for you to help with this kind of (experimental) testing?

**Comment by gytis** [comment]
I agree with running tests on OpenShift. I'll think of a way to move OrientDB tests there.

**Comment by scottmarlow** [comment]
Are there any existing solutions or (testing) implementation that we could follow for testing on OpenShift?  

I searched for continuous integration testing on OpenShift and found [this link](https://developers.openshift.com/managing-your-applications/continuous-integration.html).  Another link, is a CD/CI demo [here](https://developers.openshift.com/managing-your-applications/continuous-integration.html
https://blog.openshift.com/cicd-with-openshift/)

However we proceed, it would be great to take some small steps forward.

**Comment by gytis** [comment]
Thanks for the links, I'll find some time to watch the videos and read the articles.

I don't know of any projects. However, I didn't have a chance to look properly into it. I should have time for that on Wednesday or Thursday.

**Pull request merged**
