### PR TITLE
OrientDB feature pack

### PR DESCRIPTION
**Pull request by gytis**

### CODE REVIEW

**Comment by gytis** [comment]
@scottmarlow I've run OrientDBTestCase from nosql-dev10 and everything works. However, at some point we should introduce a testsuite module to add all the tests

**Comment by scottmarlow** [comment]
I agree that we need testing, I'm still hoping to get that in externally.

I looked at the generated OrientDB feature pack and see the following contents, sound right?

> unzip -l /home/smarlow/.m2/repository/org/wildfly/nosql/wildfly-orientdb-build/1.0.0.Alpha1-SNAPSHOT/wildfly-orientdb-build-1.0.0.Alpha1-SNAPSHOT-bin.zip 
> Archive:  /home/smarlow/.m2/repository/org/wildfly/nosql/wildfly-orientdb-build/1.0.0.Alpha1-SNAPSHOT/wildfly-orientdb-build-1.0.0.Alpha1-SNAPSHOT-bin.zip
>   Length      Date    Time    Name
> ---------  ---------- -----   ----
>         0  01-11-2017 12:49   modules/
>         0  01-11-2017 12:49   modules/system/
>         0  01-11-2017 12:49   modules/system/layers/
>         0  01-11-2017 12:49   modules/system/layers/base/
>         0  01-11-2017 12:49   modules/system/layers/base/org/
>         0  01-11-2017 12:49   modules/system/layers/base/org/wildfly/
>         0  01-11-2017 12:49   modules/system/layers/base/org/wildfly/extension/
>         0  01-11-2017 12:49   modules/system/layers/base/org/wildfly/extension/nosql/
>         0  01-11-2017 12:49   modules/system/layers/base/org/wildfly/extension/nosql/orientdb/
>         0  01-11-2017 12:49   modules/system/layers/base/org/wildfly/extension/nosql/orientdb/main/
>         0  01-11-2017 12:49   modules/system/layers/base/org/wildfly/extension/nosql/common/
>         0  01-11-2017 12:49   modules/system/layers/base/org/wildfly/extension/nosql/common/main/
>         0  01-11-2017 12:49   modules/system/layers/base/com/
>         0  01-11-2017 12:49   modules/system/layers/base/com/orientechnologies/
>         0  01-11-2017 12:49   modules/system/layers/base/com/orientechnologies/main/
>         0  01-11-2017 12:49   docs/
>         0  01-11-2017 12:49   docs/examples/
>         0  01-11-2017 12:49   docs/examples/configs/
>      2594  01-11-2017 12:49   modules/system/layers/base/org/wildfly/extension/nosql/orientdb/main/module.xml
>     79624  01-11-2017 12:49   modules/system/layers/base/com/orientechnologies/main/orientdb-client-2.1.20.jar
>     39598  01-11-2017 12:49   modules/system/layers/base/org/wildfly/extension/nosql/orientdb/main/wildfly-orientdbsubsystem-1.0.0.Alpha1-SNAPSHOT.jar
>     21224  01-11-2017 12:49   modules/system/layers/base/org/wildfly/extension/nosql/common/main/wildfly-nosql-common-1.0.0.Alpha1-SNAPSHOT.jar
>     21954  01-11-2017 12:49   docs/examples/configs/standalone-orientdb.xml
>      2527  01-11-2017 12:49   modules/system/layers/base/org/wildfly/extension/nosql/common/main/module.xml
>    286431  01-11-2017 12:49   modules/system/layers/base/com/orientechnologies/main/orientdb-graphdb-2.1.20.jar
>   3133963  01-11-2017 12:49   modules/system/layers/base/com/orientechnologies/main/orientdb-core-2.1.20.jar
>    188925  01-11-2017 12:49   modules/system/layers/base/com/orientechnologies/main/orientdb-object-2.1.20.jar
>      1870  01-11-2017 12:49   modules/system/layers/base/com/orientechnologies/main/module.xml
>     40024  01-11-2017 12:49   modules/system/layers/base/com/orientechnologies/main/orientdb-enterprise-2.1.20.jar

**Comment by gytis** [comment]
I think it's missing a couple of modules. I've tested only 
wildfly-orientdb-build-1.0.0.Alpha1-SNAPSHOT and didn't test 
wildfly-orientdb-build-1.0.0.Alpha1-SNAPSHOT-bin.
Do you just move it's content's to the normal WildFly standalone 
distribution in order to test them?

**Comment by scottmarlow** [comment]
I just tried unzipping the /home/smarlow/work/wildfly-nosql/orientdb/build/target/wildfly-orientdb-build-1.0.0.Alpha1-SNAPSHOT-bin.zip contents into a WF 10.1.0.Final distribution and do get a ModuleNotFoundException for com.googlecode.concurrentlinkedhashmap:main when starting the app server (after manually adding org.wildfly.extension.nosql.orientdb to the standalone.xml).

**Comment by gytis** [comment]
Yes that's one of the modules that I meant. Another one is 'tinkerpop'. 
I'll look why aren't they in the binary tomorrow.

**Pull request merged**
